version: "3"

services:
  app:
    build: .
    command: python hello.py
    ports:
      - "5000:5000"
    networks:
      - flask-net
    volumes:
      - .:/myapp
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root 
    volumes:
      - db-data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      - flask-net

networks:
  flask-net:
volumes:
  db-data:
